services:

  hotel-front:

    build: .

    container_name: hotel-front

    ports:
      - "9540:9540"

    restart: always

    volumes:
      - .:/app
      - /app/node_modules

    environment:
      VITE_USUARIO_API: http://academico3.rj.senac.br/20261prj5/hotel/cliente
      VITE_RESERVA_API: http://academico3.rj.senac.br/20261prj5/hotel/reserva
      VITE_QUARTO_API: http://academico3.rj.senac.br/20261prj5/hotel/quarto
      VITE_PAGAMENTO_API: http://academico3.rj.senac.br/20261prj5/hotel/pagamento
      VITE_PAGAMENTO_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiaG90ZWxfZnJvbnQiLCJleHAiOjE4MTMzMjc3NjJ9.WhDjRNe1Uhz5ibFAgcd4V_4bhJd66MAM_-9fddyzc68

    command: sh -c "npm run build && npm start"